feat: create and attach configMap when adding file after commit
celestiaorg/knuu pull request #154
Opened 2023-07-17 11:18 UTC by smuu

Tested in branch: https://github.com/celestiaorg/knuu-example/tree/feature/add-file-after-commit

Resolves https://github.com/celestiaorg/knuu/issues/32

## Overview

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-07-17 12:04 UTC, Bidon15 requested changes
some nits - otherwise lgtm next round 👍

2023-07-17 13:50 UTC, jrmanes commented on pkg/k8s/k8s_pod.go
> +	defaultMode := int32(0777)
`0777` 🥲 is it need it?, we're currently using [0550](https://github.com/celestiaorg/celestia-stack-internal/blob/main/data-availability/base/statefulset.yaml#L142) here

2023-07-24 12:10 UTC, smuu commented on pkg/k8s/k8s_configmap.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
https://github.com/celestiaorg/knuu/pull/154/commits/c5f8c59f74d8ba4b9ea4fad5fc0ad8d6e50c04a1

2023-07-24 12:13 UTC, smuu commented on pkg/k8s/k8s_pod.go
> +	defaultMode := int32(0777)
https://github.com/celestiaorg/knuu/pull/154/commits/a777854923e02c4b6ccf50b867a1f4fc052b43e3

2023-07-24 12:19 UTC, smuu commented on pkg/k8s/k8s_configmap.go
> +func ConfigMapExists(namespace, name string) (bool, error) {
https://github.com/celestiaorg/knuu/issues/160

2023-07-24 13:07 UTC, jrmanes approved these changes
LGTM after talk 👌

2023-07-24 13:55 UTC, merged