chore: integrate bittwister sdk
celestiaorg/knuu pull request #210
Opened 2023-12-06 16:49 UTC by mojtaba-esk

This PR proposes required changes to integrate [BitTwister SDK](https://github.com/celestiaorg/bittwister/tree/main/sdk) into Knuu.

The assumption is that BitTwister runs in a side car in API serve mode and the SDK communicates to it via REST endpoints.

2023-12-07 07:25 UTC, smuu commented on pkg/knuu/instance.go
> +	err := i.btClient.BandwidthStart(sdk.BandwidthStartRequest{
I'm curious how this behaves with the local knuu controller.

2023-12-07 09:17 UTC, mojtaba-esk commented on pkg/knuu/instance.go
> +		}
This code adds sidecar to every instance, I removed the condition for this stage.
We need to decide on some config param that allows users to activate it. something like
```go
i := NewInstance(...).WithTrafficShaper()
```

2023-12-15 10:06 UTC, smuu approved these changes
Again: Great work :rocket:

2023-12-15 10:07 UTC, smuu requested changes
Accidentally approved because it's so amazing

2023-12-15 10:59 UTC, mojtaba-esk commented on pkg/knuu/instance.go
> +		}
that was a mistake, I'll remove it.

2023-12-15 11:03 UTC, mojtaba-esk commented on pkg/knuu/instance_helper.go
> +	if i.BitTwister.Enabled() {
to avoid confusion, I will rename that helper function as well.

2023-12-15 11:06 UTC, mojtaba-esk commented on pkg/knuu/instance_helper.go
> +		if err := networkConfigInstance.SetEnvironmentVariable("SERVE_ADDR", fmt.Sprintf("0.0.0.0:%d", i.BitTwister.Port())); err != nil {
Very good, will do and if user want's to have a customized port in some cases, then they can do it afterwards.

2023-12-15 11:26 UTC, mojtaba-esk commented on pkg/knuu/instance_helper.go
> +		if err := networkConfigInstance.SetEnvironmentVariable("SERVE_ADDR", fmt.Sprintf("0.0.0.0:%d", i.BitTwister.Port())); err != nil {
I just checked the code and it seems like `SetImage` puts the state in `Preparing` mode and calling it after `SetImage` and before `Commit` is what you are talking about.

2023-12-15 11:29 UTC, mojtaba-esk commented on pkg/knuu/instance_helper.go
> +	if i.BitTwister.Enabled() {
Thanks for catching this point
no. fixed

2023-12-15 13:34 UTC, mojtaba-esk commented on pkg/knuu/instance_helper.go
> +		if err := networkConfigInstance.SetEnvironmentVariable("SERVE_ADDR", fmt.Sprintf("0.0.0.0:%d", i.BitTwister.Port())); err != nil {
No worries. it is fixed now. I will have a look to the code to learn about it. thanks

2023-12-19 11:31 UTC, smuu approved these changes

2023-12-19 11:58 UTC, merged