feat(example): env to json
celestiaorg/knuu pull request #307
Opened 2024-04-30 14:37 UTC by tty47

hello!

this test adds the content of the `.env` file as json into the container.

cheers! 🚀

2024-04-30 14:41 UTC, mojtaba-esk approved these changes
Well done.
Just a question, is passing envs as JSON a common practice? I mean how applications read it and how it translate it to ENV vars?

2024-04-30 15:23 UTC, mojtaba-esk commented on pkg/knuu/knuu.go
> +		return ErrCannotLoadEnv.Wrap(err)
[question] 
- Does the `.env` file have to exist for all tests?
- if it does not exist will it through an error here?

2024-05-02 10:53 UTC, smuu requested changes

2024-05-02 10:53 UTC, smuu commented on pkg/knuu/knuu.go
> +	}
Please move this to `InitializeWithScope()` so it's always loaded.

2024-05-03 07:24 UTC, smuu requested changes
Nice one, only small things

2024-05-03 07:24 UTC, smuu commented on .env.example
> +DEBUG_LEVEL=info # The debug level. debug, info, warn, error
I think this is called `LOG_LEVEL`

```suggestion
LOG_LEVEL=info # The debug level. debug, info, warn, error
```

2024-05-03 07:24 UTC, smuu commented on .env.example
Having this `.env` in this repo with good values would be nice when we run the tests.

2024-05-03 07:35 UTC, smuu approved these changes
Let's go! :rocket:

2024-05-03 07:36 UTC, merged