fix: add files to image issue
celestiaorg/knuu pull request #596
Opened 2024-12-13 16:47 UTC by mojtaba-esk

Closes #595

2024-12-16 09:10 UTC, smuu requested changes
It looks got to me so far.
But before merging, let's test these changes with the celestia-app and celestia-node integration.

2024-12-18 11:52 UTC, mojtaba-esk commented on pkg/instance/build.go
> +}
that';s the exact purpose, when no files added before `Commit` but a volume is added, there is nothing to be built inside the initImage and no init container is required.

2025-01-09 15:09 UTC, smuu approved these changes
This is great, thank you!

2025-03-05 14:20 UTC, MSevey approved these changes

2025-05-16 07:22 UTC, closed without merging